// Get Columns Data
export const GET_COLUMNS_DATA = "GET_COLUMNS_DATA";
export const GET_COLUMNS_DATA_SUCCESS = "GET_COLUMNS_DATA_SUCCESS";
export const GET_COLUMNS_DATA_FAILURE = "GET_COLUMNS_DATA_FAILURE";


// Get Tasks Data
export const GET_TASK_DATA = "GET_TASK_DATA";
export const GET_TASK_DATA_SUCCESS = "GET_TASK_DATA_SUCCESS";
export const GET_TASK_DATA_FAILURE = "GET_TASK_DATA_FAILURE";


// Set Columns Data
export const ADD_COLUMNS_DATA = "ADD_COLUMNS_DATA";
export const ADD_COLUMNS_DATA_SUCCESS = "ADD_COLUMNS_DATA_SUCCESS";
export const ADD_COLUMNS_DATA_FAILURE = "ADD_COLUMNS_DATA_FAILURE";


// Set Tasks Data
export const ADD_TASK_DATA = "ADD_TASK_DATA";
export const ADD_TASK_DATA_SUCCESS = "ADD_TASK_DATA_SUCCESS";
export const ADD_TASK_DATA_FAILURE = "ADD_TASK_DATA_FAILURE";
